import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });



export default function RootLayout({ children,pageTitle, pageDescription }) {
  const title = pageTitle || "Create Next App";
  const description = pageDescription || "Generated by create next app";


  return (
    <html lang="en">
      {/*  */}
        <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
